spring:
  application:
    name: lms-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/lms_db
    username: lms_user
    password: lms_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

logging:
  level:
    com.mybank.lms: DEBUG
    org.springframework.web: DEBUG
